### ISSUE TITLE
Slow when syntax is off

### ISSUE THREAD

**Issue by denten** [nelstrom/vim-markdown-folding#16]
The plugin adds more than 2000ms to start up when syntax if off. This, I believe, is due to the `lineisfenced()` function that uses an `hassurroundingmarks()' that has slow regex parsing (well, slower than the syntax highlighter).

**Comment by nelstrom** [comment]
This is by design.

I'm being opinionated in my assumption that people who enable folding will already have syntax highlighting enabled. If syntax highlighting is disabled, I provide a fallback folding function which does the job but with poor performance.
