### ISSUE TITLE
Nesting of header levels?

### ISSUE THREAD

**Issue by hansdude** [nelstrom/vim-markdown-folding#20]
Consider the following document:

    # H1

    stuff

    ## H2

    stuff

    ### H3

    stuff

Currently I get these folds:

    # H1 [3 lines]
    ## H2 [3 lines]
    ### H3 [2 lines]

But I really want nested folds:

    # H1 [8 lines]

Expanded:

    # H1

    stuff

    ## H2 [5 lines]

Etc.

Thoughts?

**Comment by nelstrom** [comment]
vim-markdown-folding supports [two different folding styles](https://github.com/nelstrom/vim-markdown-folding/blob/110f8145d3feb584e2dfe0e990e993f335772f0c/doc/markdown-folding.txt#L35-L57) already. You can switch between them by running:

    :FoldToggle

**Comment by gunar** [comment]
I've been looking for this. Awesome! Could I set this up as a configuration in my `vimrc`?
